```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy = TRUE)
library("plyr")
library("readr")
library("tidyverse")
library("magrittr")

```

# Themes for this doc

<div class="btn-group" role="group" aria-label="...">
  <a href="exam-dark.html" class="btn btn-`r ifelse(templateFile == "dark", "info disabled", "default")`">Dark</a>
  <a href="exam-light.html" class="btn btn-`r ifelse(templateFile == "light", "info disabled", "default")`">Light</a>
  <a href="exam-material.html" class="btn btn-`r ifelse(templateFile == "material", "info disabled", "default")`">Material</a>
</div>

# Basics {.tabset .tabset-fade .tabset-pills}

```{r child = 'basics.Rmd'}
```


# dplyr (Data Manipulation) {.tabset .tabset-pills .tabset-fade}

```{r child = 'dplyr.Rmd'}
```


# magrittr (pipe opperator)

```{r child = 'magrittr.Rmd'}
```

# Plot {.tabset .tabset-pills .tabset-fade}

```{r child = 'plot.Rmd'}
```


# Classification and Resampling {.tabset .tabset-pills .tabset-fade}

```{r child = 'classification.Rmd'}
```


# Classification and Regression {.tabset .tabset-pills .tabset-fade}

```{r child = 'regression.Rmd'}
```

# ForCats (working with factors) 
```{r child = 'forcats.Rmd'}
```